osx_image: xcode10
language: objective-c
branches:
  only:
  - master
before_install:
  - gem install cocoapods
  - gem install xcpretty -N
  - cd Example ; pod install ; cd ..
script:
  - set -o pipefail
  - travis_retry xcodebuild test -workspace Example/TinySwift.xcworkspace -scheme TinySwift-Example -destination 'platform=iOS Simulator,name=iPhone 8' | xcpretty -c
  - pod lib lint
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
